[{"id":1050880140,"node_id":"R_kgDOPqMojA","name":"CVE-2025-57833","full_name":"Mkway/CVE-2025-57833","private":false,"owner":{"login":"Mkway","id":34364080,"node_id":"MDQ6VXNlcjM0MzY0MDgw","avatar_url":"https://avatars.githubusercontent.com/u/34364080?v=4","url":"https://api.github.com/users/Mkway","html_url":"https://github.com/Mkway","type":"User","site_admin":false},"html_url":"https://github.com/Mkway/CVE-2025-57833","description":"We've set up an environment to test CVE-2025-57833. This environment was built using AI, so it's subject to ongoing modification.","fork":false,"url":"https://api.github.com/repos/Mkway/CVE-2025-57833","created_at":"2025-09-05T05:03:29Z","updated_at":"2025-09-08T01:13:45Z","pushed_at":"2025-09-08T01:13:42Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"master","score":1},{"id":1053407556,"node_id":"R_kgDOPsm5RA","name":"Django-faille-CVE-2025-57833_test","full_name":"loic-houchi/Django-faille-CVE-2025-57833_test","private":false,"owner":{"login":"loic-houchi","id":194474185,"node_id":"U_kgDOC5dwyQ","avatar_url":"https://avatars.githubusercontent.com/u/194474185?v=4","url":"https://api.github.com/users/loic-houchi","html_url":"https://github.com/loic-houchi","type":"User","site_admin":false},"html_url":"https://github.com/loic-houchi/Django-faille-CVE-2025-57833_test","description":"","fork":false,"url":"https://api.github.com/repos/loic-houchi/Django-faille-CVE-2025-57833_test","created_at":"2025-09-09T12:08:05Z","updated_at":"2025-09-09T16:05:05Z","pushed_at":"2025-09-09T12:09:29Z","stargazers_count":1,"watchers_count":1,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":1,"default_branch":"main","score":1}]