[{"id":995299992,"node_id":"R_kgDOO1MSmA","name":"django-vulnerability-CVE-2025-32873","full_name":"Apollo-R3bot/django-vulnerability-CVE-2025-32873","private":false,"owner":{"login":"Apollo-R3bot","id":148726450,"node_id":"U_kgDOCN1isg","avatar_url":"https://avatars.githubusercontent.com/u/148726450?v=4","url":"https://api.github.com/users/Apollo-R3bot","html_url":"https://github.com/Apollo-R3bot","type":"User","site_admin":false},"html_url":"https://github.com/Apollo-R3bot/django-vulnerability-CVE-2025-32873","description":"Django Security Issue (CVE-2025-32873)","fork":false,"url":"https://api.github.com/repos/Apollo-R3bot/django-vulnerability-CVE-2025-32873","created_at":"2025-06-03T09:16:38Z","updated_at":"2025-06-03T09:19:59Z","pushed_at":"2025-06-03T09:34:24Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1}]