[{"id":1050326603,"node_id":"R_kgDOPpq2Sw","name":"Python-Pwnkit-CVE-2021-4034-exploit","full_name":"radzek15/Python-Pwnkit-CVE-2021-4034-exploit","private":false,"owner":{"login":"radzek15","id":79796741,"node_id":"MDQ6VXNlcjc5Nzk2NzQx","avatar_url":"https://avatars.githubusercontent.com/u/79796741?v=4","url":"https://api.github.com/users/radzek15","html_url":"https://github.com/radzek15","type":"User","site_admin":false},"html_url":"https://github.com/radzek15/Python-Pwnkit-CVE-2021-4034-exploit","description":"","fork":false,"url":"https://api.github.com/repos/radzek15/Python-Pwnkit-CVE-2021-4034-exploit","created_at":"2025-09-04T09:19:29Z","updated_at":"2025-09-04T09:19:29Z","pushed_at":"2025-09-04T09:19:29Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1}]